### ISSUE TITLE
Implement scattering of an irregular linear array of spheres

### ISSUE THREAD

**Issue by ronandrevon** [ronandrevon/pyScatSpheres#2]
adapt base class **HardSphereArrayBase** and class **QdotSphereArray** in case kd is a list(or np.array)
     - Validate by checking [continuity of the wave function and radial derivatives at interfaces](https://pyscatspheres.readthedocs.io/en/latest/linear_array_qdot_sphere/#continuity-relations) 
     - optional convergence test using **HardSphereArrayBase.test_convergence()** 
     - Example case N=5,10,20;   ka=1; kd=2.5*ka+eps*np.random.rand(N);  nref=1.1 where esp varies  in 0-0.5.
     - Show far field with **show_ff** for each values of eps
     - Show sigma(eps) for N=5,10 et 20 using **HardSphereArrayBase.get_s()**

**Comment by kitine** [comment]
Continuity check : 
<img width="263" alt="continuité1" src="https://user-images.githubusercontent.com/62999489/128646811-4d0def81-5a8b-4d22-a549-81cd72fa1383.png">
<img width="423" alt="continuité2" src="https://user-images.githubusercontent.com/62999489/128646814-be195056-1e03-403c-9c1c-9edc0a324365.png">

**Comment by kitine** [comment]
Convergence test : 
<img width="838" alt="test cv" src="https://user-images.githubusercontent.com/62999489/128646831-577a53c0-3d45-4480-8880-04413ade0a5e.png">
for nmax=3, ok

**Comment by kitine** [comment]
Far field for each value of eps : 
N=5
<img width="575" alt="far field" src="https://user-images.githubusercontent.com/62999489/128646905-5e723b9f-cfd4-4ca0-93dd-fc2f2b14949f.png">
N=10
<img width="550" alt="far field2" src="https://user-images.githubusercontent.com/62999489/128646907-4966257e-ea78-4e90-a1a7-b0feede89f7d.png">
N=20
<img width="564" alt="far field3" src="https://user-images.githubusercontent.com/62999489/128646909-b6733336-fc89-475d-b7ec-8321048530c9.png">

**Comment by kitine** [comment]
Sigma(eps) for N=5,10 et 20 : 
<img width="293" alt="sectioneff" src="https://user-images.githubusercontent.com/62999489/128646942-2da59695-ee05-4a94-bde9-747173cf7219.png">
Red : N=5
Green : N=10 
Blue : N=20
