### ISSUE TITLE
Extend code to handle arbitrary configration of spheres 

### ISSUE THREAD

**Issue by ronandrevon** [ronandrevon/pyScatSpheres#3]
Using the [translation theorem](https://pyscatspheres.readthedocs.io/en/latest/spherical_coords.html#translational-addition-theorem) for spherical harmonics including values of m>0, the formulation can be written to allow for solving the problem with arbitrary configurations of quantum dots. 
A new base class would have to be implemented similar to **HardSphereArrayBase**.

**Comment by kitine** [comment]
**Continuity check :**
![i](https://user-images.githubusercontent.com/62999489/129163595-c11b5205-0bdc-4df4-bea8-bd987ea81cc1.jpg)
![Capture d’écran 2021-08-12 101805](https://user-images.githubusercontent.com/62999489/129163601-b12292b6-ab12-4214-b179-63b2520f8053.jpg)
![tot](https://user-images.githubusercontent.com/62999489/129163617-32462ad5-33cd-4a03-94c4-8be41c8c16d0.jpg)
![Capture d’écran 2021-08-12 102619](https://user-images.githubusercontent.com/62999489/129164241-d6bf6cfa-ed83-451d-8c1e-200e0dfb3030.jpg)

**Comment by ronandrevon** [comment]
stable
